### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shunichironomura** [shunichironomura/capsula#1]
# Roadmap

This issue is for brainstorming (not promising) on Capsula's roadmap.

Capsula has three core functions: 

1. Context capture
2. Execution monitoring
3. Context reproduction

## Context capture

- [x] Python version
- [x] Platform
- [x] Python dependencies and their versions
- [x] #131
- [x] Environment variables (that are explicitly specified)
- [x] Git commit hash
- [x] Git diff (if the dirty state is allowed. as a patch file)
- [x] Hash of specified files
- [ ] #152
- [x] Allow to add a custom context item

### General

- [x] Execution start time, end time, and duration
- [x] Working directory
- [x] #126
- [x] Hash of output files

### CLI

- [x] Comment line arguments
- [x] stdout and stderr
- [x] Exit code

### Decorator

- [x] Python function name, file, and line number
- [x] Python function arguments
- [x] #127
- [x] Raised exception
- [ ] Logging output
- [ ] Custom logging insertion using module-level function

## Context reproduction

- [ ] #130
- [x] #128

## Miscellaneous

- [ ] `capsula init` command to generate `capsula.toml` file
- [x] #109
- [x] #15
- [x] #28
- [ ] #129

**Comment by shunichironomura** [comment]
Closing this issue as the remained tasks are either turned into a sub-issue for future reference, or should be ignored.

As for the ignored tasks:
- Logging output and custom logging insertion: Should be taken care of by other libraries. `capsula.record` can do some of what they want?
- `capsula init` We should instead minimize the required configuration, i.e., works out of the box.
